### ISSUE TITLE
Personal access token does not trigger page build

### ISSUE THREAD

**Issue by tuliren** [tuliren/publish-gitbook#2]
When I test the action in [gitbook-template](https://github.com/tuliren/gitbook-template), it seems that even a personal access token cannot trigger a page build. There are similar complaints [here](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/42635/highlight/true#M5066). May need to try [this trick](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/43192/highlight/true#M5281):

```yml
- name: Request Github Pages build job
  run: >-
    curl -L -X POST 
    -H "Content-Type: application/json"
    -H "Authorization: token ${{ secrets.GH_PAT}}"
    "https://api.github.com/repos/${{ github.repository }}/pages/builds"
```

**Comment by funwhilelost** [comment]
Hmm.. interesting.  I have it working with the personal access token.  It is a private repo, though, which I hear makes a difference.  Thanks for cleaning up my PR!

https://seattledeveloperscoop.github.io/seattledeveloperscoop-book/

**Comment by tuliren** [comment]
Got it. Good to know that it works for private repo. Thanks again for your PR.

**Comment by tuliren** [comment]
This issue has been resovled. Confirmed that `GITHUB_TOKEN` now works for public and private repos.
